name: Frontend CI/CD

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - staging
      - master
    types:
      - opened
      - synchronize
      - reopened
      - closed

concurrency:
  group: frontend-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-reusable-workflow:
    name: Frontend CI/Deploy
    uses: zenos-work/zenos-infra/.github/workflows/frontend-ci-deploy.yml@development
    with:
      environment: ${{ (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'staging' && github.event.pull_request.head.ref == 'development') && 'staging' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'master' && github.event.pull_request.head.ref == 'staging') && 'production' || 'staging' }}
      run_deploy: ${{ (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && (github.event.pull_request.base.ref == 'staging' || github.event.pull_request.base.ref == 'master')) }}
      min_coverage: ${{ vars.FRONTEND_MIN_COVERAGE || '80' }}
    secrets: inherit
